#!/usr/bin/env bash
# This script coducts a file transfer from a client to a server depending on parameters parsed

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	touch "$1"
	scp -i "$4" "./$1" "$3"@"$2":~/
fi
