#!/usr/bin/env bash
# This script is for displaying "Best School" 10 times

list=('Best School' 'Best School' 'Best School' 'Best School' 'Best School'
	'Best School' 'Best School' 'Best School' 'Best School' 'Best School')

for i in "${list[@]}"
do
	echo "$i"
done
