#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 9 ]
    then
	echo "Hi"
   	count=$((count + 1))
    else
	echo "Best School"
   	count=$((count + 1))
    fi
done
