#!/usr/bin/env bash
# This script is for displaying "Best School" 9 times and then "Hi"

i="1"
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
