#!/usr/bin/env bash
#This script gives information about a file

fil="school"

if [ -e $fil ]
then
    echo "school file exists"
    if [ -s $fil ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
    if [ -f $fil ]
    then
	echo "school is a regular file"
    else
        :
    fi
else
    echo "school file does not exist"
fi
