#!/usr/bin/env bash
# This script configures an Ubuntu server

# Creating a copy of /etc/hosts
cp /etc/hosts ~/hosts.new

# Using sed to modify ~/hosts.new
sed -i 's/^127\.0\.0\.1[[:space:]]*localhost$/127.0.0.2 localhost/' ~/hosts.new
sed -i '/^127\.0\.0\.2[[:space:]]*localhost$/a 8.8.8.8\tfacebook.com' ~/hosts.new

# Overwriting /etc/hosts with the modified ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts

# Display the updated /etc/hosts
sudo cat /etc/hosts

# Exiting script
exit 0
